services:
  nginx:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"        
      - "8000:80"          
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - MONGO_URI=mmongodb+srv://charleschiu0475:IJQHZ63NzCyHqe7P@cluster0.dnycdks.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
