services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/tmp/hls

  web:
    build: .
    container_name: express-web
    ports:
      - "8000:8000"
    volumes:
      - ./public:/app/public
    depends_on:
      - nginx-rtmp
